### ISSUE TITLE
plugin_api失敗時にorgのリンクになってしまう

### ISSUE THREAD

**Issue by ghost** [inc2734/wp-github-plugin-updater#13]
何らかの弾みでplugins_apiが失敗した際は、externalがtrueにならない時がある。
その場合、プラグイン詳細の「プラグインホームページ」のリンクが、
「WordPress.orgのプラグインページ」としてリンクが表示される。

_plugins_apiファンクションに

$obj->external = true;

を追加して、externalを強制的に常にtrueにすれば対策できる。（常にtrueにしておいてもその他の影響はなさそう）

**Comment by ghost** [comment]
https://github.com/WordPress/WordPress/blob/3a85c4741be6ae09027c71ddf78dbb61ae9296d9/wp-admin/includes/plugin-install.php#L222

と、

https://github.com/WordPress/WordPress/blob/3a85c4741be6ae09027c71ddf78dbb61ae9296d9/wp-admin/includes/plugin-install.php#L699

の辺りかな

**Comment by ghost** [comment]
あ、ついでに調べたら…

$downloadlink は、 $download_link っぽいです。ハイフンが抜けているかも。

https://github.com/WordPress/WordPress/blob/3a85c4741be6ae09027c71ddf78dbb61ae9296d9/wp-admin/includes/plugin-install.php#L854

$download_link で package のzipのURLを設定すれば「今すぐ更新する」などのボタンが表示され、詳細からも更新できる事を確認。

多分、詳細画面の問題は、これくらいかもです。
（プルリクしようとしたら…修正ありがとうございますw

**Comment by inc2734** [comment]
`external` しりませんでした！ `external => true` の追加と、`$downloadlink` → `$download_link` の変更をいれました。
