### ISSUE TITLE
No responseの場合の対応

### ISSUE THREAD

**Issue by ghost** [inc2734/wp-github-plugin-updater#5]
エラーログより調べましたので、共有します。
（こちらで修正＆プルリク考えています）

そもそも`state`が、数値で返却されない場合がある（200とかではなく空文字を返している場合があった）
`wp_remote_retrieve_response_code`を見ると`return '';`があるのでこのパターンになっていると思われます。その場合、`$body`も空(null？)になるっぽいので`message`を持たない。
結果として、そのパターン時は、強制的にNo responseがmessageに代入され、警告が出る状態となっている。

修正する案として…

1. 更新画面じゃない場合は一切の警告を出さない（投稿一覧などでプラグインアップデートに関する警告が出てきても混乱を招く為）

2. 空文字の場合もreturnして警告を出さない（そもそも更新チェック自体が適切に行われてない時にこのパターンが起こってるっぽい。公式プラグインの場合は何も警告を出してないしこちらも何も出さなくて良いのではないか）

3. 更新画面時、かつ、200 OKで`message`がある場合のみ、それが原因なので現在のメッセージで良いと思われるが、`message`が無い場合に`No response`は`message`の警告文理由としては不適切と思われる。その場合のメッセージを変更（プラグインの更新チェックに失敗しました とか）する。

って感じですが、どうでしょう？

**Comment by inc2734** [comment]
> wp_remote_retrieve_response_codeを見るとreturn '';がある

あーなるほど、そういうことですね。確かに今のコードだと正しいレスポンスコードが帰ってこなかったときのことを想定できてないですね。2か3が良いと思いますが、3のほうが丁寧ですかねぇ。通信先が GitHub API で、本来リクエストを送ればレスポンスが返ってくるはずで、返ってこないというのは何らか異常があったときだと思うので。

そんな感じでこちらで修正いれますよ！

**Comment by ghost** [comment]
Oh…。プルリクとコメントが入れ違ってた（汗

結構お手数かけて申し訳ないです。
一応、プルリクを送ったのでそちらで調整していただければー。

**Comment by inc2734** [comment]
プルリクめちゃはや！と思ったら入れ違いでしたか笑
頂いたプルリクみてたら確かに1の対応もしたほうがベターかな…という気がしてきました。

PHPMD が警告だしてるみたいなので、マージした後こちらで修正いれます。ありがとうございますー！
